name: Deployment
on: [push]
jobs:
  Deploy:
    runs-on: self-hosted
    
    steps:
      - name: Compile and build snippets
        run: |
          cd ~/actions-runner/_work/docs_compiler
          node .
      - name: Push new snippets to repository
        continue-on-error: true
        run: |
          cd ~/actions-runner/_work/docs_compiler
          cd dist
          git commit -m "Update snippets"
          git push
      - name: Build and publish VSCode extension
        run: |
          cd ~/actions-runner/_work/docs_compiler
          cd dist/vscode
          vsce package      
      - name: vsce publish
        uses: sigma/vsce-publish-action@b888dc8468ce39a3e940118f65f47a43ff1570cb
              sigma/vsce-publish-action@v0.0.2
              https://github.com/gamesensical/docs/commit/1530a290e3a33f72a9501a83c46f049e5c993a8b
