name: Deployment
on: [push]
jobs:
- runs-on: ubuntu-latest  
  Deploy: self-hosted 
          ubuntu-latest
          node . 
          Compile and build snippets
         Run: |
          continue-on-error: true 
          cd ~/actions-runner/_work/docs_compiler
          cd dist
          git commit -m "Update snippets"
          git push
          cd ~/actions-runner/_work/docs_compiler
          cd dist/vscode
          vsce package      
          vsce publish      
          sigma/vsce-publish-action@b888dc8468ce39a3e940118f65f47a43ff1570cb
          sigma/vsce-publish-action@v0.0.2
          Cache
          actions/cache@v3.0.11
          https://raw.githubusercontent.com/gamesensical/docs/1530a290e3a33f72a9501a83c46f049e5c993a8b/.github/workflows/deploy.yml
run-name: 1530a290e3a33f72a9501a83c46f049e5c993a8b
